name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain, cache
        uses: moonrepo/setup-rust@v0
        with:
          channel: 1.73.0
          cache-target: dev
          components: clippy
      - run: cargo +1.73.0 fmt --check
      - run: cargo +1.73.0 clippy
  miri-test:
    name: Miri Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain, cache
        uses: moonrepo/setup-rust@v0
        with:
          channel: nightly
          cache-target: dev
          components: miri
      - run: cargo +nightly miri test